---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks: 
  - name: Add a new tenant
    aci_tenant:
      host: "{{ aci_url }}"
      username: "{{ aci_user }}"
      password: "{{ aci_password }}"
      tenant: "{{ tenant }}" 
      description: "{{ tenant_desc }}"
      state: present
      validate_certs: no
    delegate_to: localhost


  - name: Add a new VRF to a tenant
    aci_vrf:
      host: "{{ aci_url }}"
      username: "{{ aci_user }}"
      password: "{{ aci_password }}"
      vrf: "{{ vrf }}"
      tenant: "{{ tenant }}"
      descr: "{{ vrf_desc }} VRF"
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
      validate_certs: no
    delegate_to: localhost
